# Generated by Django 5.2.1 on 2025-11-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0012_alter_slidersettings_delay'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slidersettings',
            options={'verbose_name': 'Настройки слайдера', 'verbose_name_plural': 'Настройки слайдера'},
        ),
        migrations.AddField(
            model_name='slidersettings',
            name='auto',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='slidersettings',
            name='loop',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='slidersettings',
            name='name',
            field=models.CharField(default='default', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='slidersettings',
            name='navs',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='slidersettings',
            name='pags',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='slidersettings',
            name='stop_mouse_hover',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='slidersettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='slidersettings',
            name='delay',
            field=models.IntegerField(default=5),
        ),
    ]
