# Generated by Django 5.2.1 on 2025-11-19 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0010_companycertificate_companyhistory_companyrequisite_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delay', models.PositiveIntegerField(default=5, help_text='Задержка между слайдами (секунды)')),
            ],
        ),
        migrations.RemoveField(
            model_name='companycertificate',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='companyhistory',
            name='image',
        ),
    ]
