# Generated by Django 5.2.1 on 2025-11-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0011_slidersettings_remove_companycertificate_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slidersettings',
            name='delay',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
